import { CronExpressionParser } from "cron-parser";

import type { CustomSchedule } from "./config";

// Compiles wizard-defined recurring jobs into eve schedule files. Each one
// runs the prompt as a fresh session and delivers the result into a new web
// chat thread — the same path fired reminders use, so it works even when the
// proactive feature (reminder tools) is off.

export function validCron(expression: string): boolean {
  try {
    CronExpressionParser.parse(expression);
    return true;
  } catch {
    return false;
  }
}

export function scheduleSlug(name: string, index: number): string {
  const slug = name
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, "-")
    .replaceAll(/^-+|-+$/g, "")
    .slice(0, 40);
  return slug.length > 0 ? slug : `job-${index + 1}`;
}

export function generateScheduleFile(schedule: CustomSchedule): string {
  const title = JSON.stringify(schedule.name);
  const message = JSON.stringify(
    [
      `Scheduled job ${schedule.name} just fired. Its instruction:`,
      "",
      schedule.prompt,
      "",
      "Carry it out now and deliver the result. The user didn't just message you - this is proactive, so lead with what this is about.",
    ].join("\n"),
  );
  return `import { defineSchedule } from "eve/schedules";

import { deliverToWebChatThread } from "../lib/web-thread-delivery";

// Generated by the eveclaw agent builder: "${schedule.name.replaceAll(/[*/]/g, "")}".
// Runs the stored prompt as a fresh session and lands it as a web chat thread.
export default defineSchedule({
  cron: ${JSON.stringify(schedule.cron)},
  async run({ waitUntil }) {
    waitUntil(
      deliverToWebChatThread(${title}, ${message}, "reminder").catch((error) => {
        console.error("Scheduled job failed:", error);
      }),
    );
  },
});
`;
}
